"""unit tracking columns

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-25 00:11:06.899779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('input_hash', sa.String(), nullable=True))
    op.add_column('unit', sa.Column('cost_json', sa.Text(), nullable=True))
    op.add_column('unit', sa.Column('llm_raw_output', sa.Text(), nullable=True))
    op.add_column('unit', sa.Column('needs_reconsolidation', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'needs_reconsolidation')
    op.drop_column('unit', 'llm_raw_output')
    op.drop_column('unit', 'cost_json')
    op.drop_column('unit', 'input_hash')
    # ### end Alembic commands ###
