"""worker heartbeat columns

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-25 08:24:35.515353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('worker_id', sa.String(), nullable=True))
    op.add_column('unit', sa.Column('heartbeat_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'heartbeat_at')
    op.drop_column('unit', 'worker_id')
    # ### end Alembic commands ###
