"""Cypher export writer: parquet DataFrames + embedding dicts -> Cypher script.

The writer is pure (no graphrag imports, no I/O). The route loads parquet +
LanceDB vectors and hands them in. Output is an idempotent Cypher script that
MERGE-upserts entities, relationships, text units, and (when supplied) vector
indexes + vector properties into Neo4j >= 5.11.

Every `:param rows => <JSON>` line's right-hand side is valid JSON
(``json.loads`` must not raise) — the writer therefore serializes with
``json.dumps(rows, ensure_ascii=False)`` and never hand-rolls Cypher escaping.
"""

from __future__ import annotations

import json
import math
from collections.abc import Iterator
from typing import Any

import pandas as pd

_BATCH = 500


def _coerce(value: Any) -> Any:
    """Coerce a parquet cell into a JSON-serializable Python value.

    - None / NaN / NA / NaT -> None
    - numpy scalar -> native Python int/float/bool
    - ndarray / list / tuple / Series -> list (recursively coerced)
    - everything else passes through (str, bool, int, float)
    """
    import numpy as np

    if value is None:
        return None
    if isinstance(value, float) and math.isnan(value):
        return None
    if value is pd.NA or value is pd.NaT:
        return None
    if isinstance(value, np.generic):
        v = value.item()
        if isinstance(v, float) and math.isnan(v):
            return None
        return v
    if isinstance(value, np.ndarray):
        return [_coerce(v) for v in value.tolist()]
    if isinstance(value, (list, tuple)):
        return [_coerce(v) for v in value]
    if isinstance(value, pd.Series):
        return [_coerce(v) for v in value.tolist()]
    return value


def _row_dict(row: pd.Series) -> dict:
    return {col: _coerce(val) for col, val in row.items()}


def _batches(rows: list[dict], size: int = _BATCH) -> Iterator[list[dict]]:
    for i in range(0, len(rows), size):
        yield rows[i : i + size]


def _emit_param_block(lines: list[str], rows: list[dict]) -> None:
    lines.append(f":param rows => {json.dumps(rows, ensure_ascii=False)};")
    lines.append("UNWIND $rows AS row")


def write_cypher(
    entities: pd.DataFrame,
    relationships: pd.DataFrame,
    text_units: pd.DataFrame | None = None,
    entity_embeddings: dict[str, list[float]] | None = None,
    text_unit_embeddings: dict[str, list[float]] | None = None,
) -> str:
    """Render an idempotent Cypher load script.

    Only entities + relationships are required. TextUnit nodes + FROM_CHUNK
    edges are emitted when ``text_units`` is supplied (Task 2). Vector indexes
    + vector properties are emitted when the corresponding embedding dict is
    supplied and non-empty (Task 3).
    """
    lines: list[str] = []
    lines.append("// Cypher load script generated by KB Platform.")
    lines.append("// Load with: cypher-shell -a <uri> -u <user> -p <pw> -f load.cypher")
    lines.append("// Requires Neo4j >= 5.11 (vector index + node vector property load).")
    lines.append("// Idempotent: MERGE / IF NOT EXISTS; safe to re-run after a reindex.")
    lines.append("")
    _emit_schema_preamble(lines)
    _emit_entities(lines, entities)
    _emit_relationships(lines, relationships)
    # TextUnit nodes + FROM_CHUNK edges when supplied (Task 2).
    # Vector indexes + vector properties when supplied (Task 3).
    if text_units is not None:
        _emit_text_units(lines, text_units, entities)
    if entity_embeddings:
        _emit_vector_index(lines, "entity_description_vec", "Entity", "entity_description", "title", entity_embeddings)
    if text_unit_embeddings:
        _emit_vector_index(lines, "text_unit_text_vec", "TextUnit", "text_unit_text", "id", text_unit_embeddings)
    return "\n".join(lines) + "\n"


def _emit_schema_preamble(lines: list[str]) -> None:
    lines.append("// 1. Schema preamble (idempotent)")
    lines.append("CREATE CONSTRAINT entity_title_unique IF NOT EXISTS FOR (e:Entity) REQUIRE e.title IS UNIQUE;")
    lines.append("CREATE INDEX entity_type IF NOT EXISTS FOR (e:Entity) ON (e.type);")
    lines.append("")


def _emit_entities(lines: list[str], entities: pd.DataFrame) -> None:
    lines.append(f"// 2. Entities ({len(entities)} rows)")
    rows = [_row_dict(row) for _, row in entities.iterrows()] if len(entities) else []
    for batch in _batches(rows):
        _emit_param_block(lines, batch)
        lines.append("MERGE (e:Entity {title: row.title})")
        lines.append("SET e += row;")
    lines.append("")


def _emit_relationships(lines: list[str], relationships: pd.DataFrame) -> None:
    lines.append(f"// 3. Relationships ({len(relationships)} rows)")
    rows: list[dict] = []
    for _, row in relationships.iterrows():
        d = _row_dict(row)
        source = d.pop("source", None)
        target = d.pop("target", None)
        rows.append({"source": source, "target": target, "_p": d})
    for batch in _batches(rows):
        _emit_param_block(lines, batch)
        lines.append("MATCH (s:Entity {title: row.source}), (t:Entity {title: row.target})")
        lines.append("MERGE (s)-[r:RELATED]->(t)")
        lines.append("SET r += row._p;")
    lines.append("")


# --- Stubs filled in by Tasks 2 and 3. ---------------------------------------
def _emit_text_units(lines: list[str], text_units: pd.DataFrame, entities: pd.DataFrame) -> None:
    lines.append(f"// 4. Text units ({len(text_units)} rows)")
    # The TextUnit uniqueness constraint lives with the TextUnit load so that
    # scripts without text_units carry no :TextUnit artifacts at all.
    lines.append(
        "CREATE CONSTRAINT text_unit_id_unique IF NOT EXISTS FOR (t:TextUnit) REQUIRE t.id IS UNIQUE;"
    )
    valid_ids = set(text_units["id"].astype(str)) if "id" in text_units.columns else set()
    rows = [_row_dict(row) for _, row in text_units.iterrows()] if len(text_units) else []
    for batch in _batches(rows):
        _emit_param_block(lines, batch)
        lines.append("MERGE (t:TextUnit {id: row.id})")
        lines.append("SET t += row;")
    # FROM_CHUNK edges: (:TextUnit)-[:FROM_CHUNK]->(:Entity), derived from
    # each entity's text_unit_ids. Orphans (text_unit id absent from the
    # text_units set) are dropped at write time.
    from_chunk: list[dict] = []
    if "text_unit_ids" in entities.columns and "title" in entities.columns:
        for _, ent in entities.iterrows():
            title = _coerce(ent["title"])
            ids = ent["text_unit_ids"]
            if ids is None:
                continue
            id_list = ids.tolist() if hasattr(ids, "tolist") else list(ids)
            for tu_id in id_list:
                tu_id = str(tu_id)
                if tu_id in valid_ids:
                    from_chunk.append({"tu_id": tu_id, "entity_title": title})
    lines.append(f"// 4b. FROM_CHUNK edges ({len(from_chunk)} rows)")
    for batch in _batches(from_chunk):
        _emit_param_block(lines, batch)
        lines.append("MATCH (t:TextUnit {id: row.tu_id}), (e:Entity {title: row.entity_title})")
        lines.append("MERGE (t)-[:FROM_CHUNK]->(e);")
    lines.append("")


def _emit_vector_index(
    lines: list[str],
    index_name: str,
    label: str,
    prop: str,
    key_col: str,
    embeddings: dict[str, list[float]],
) -> None:
    """Emit CREATE VECTOR INDEX + batched setNodeVectorProperty.

    ``key_col`` is the node's identity property name used in the MATCH
    ("title" for Entity, "id" for TextUnit); the param-row key is always
    renamed to the Cypher bind variable expected by the MATCH. Dimensions
    are detected from the first vector; similarity is cosine.
    """
    sample = next(iter(embeddings.values()), None)
    if not sample:
        return
    dim = len(sample)
    var = "e" if label == "Entity" else "t"
    key_in_row = "title" if key_col == "title" else "tu_id"
    lines.append(f"// Vector index: {label}.{prop}")
    lines.append(f"CREATE VECTOR INDEX {index_name} IF NOT EXISTS")
    lines.append(f"  FOR ({var}:{label}) ON ({var}.{prop})")
    lines.append(
        f"  OPTIONS {{ indexConfig: {{ `vector.dimensions`: {dim}, "
        f'`vector.similarity_function`: "cosine" }} }};'
    )
    rows = [{key_in_row: k, "vec": [float(x) for x in v]} for k, v in embeddings.items()]
    for batch in _batches(rows):
        _emit_param_block(lines, batch)
        match_key = "row.title" if key_col == "title" else "row.tu_id"
        lines.append(f"MATCH ({var}:{label} {{{key_col}: {match_key}}})")
        lines.append(f'CALL db.create.setNodeVectorProperty({var}, "{prop}", row.vec);')
    lines.append("")
